<a href="https://colab.research.google.com/github/Rashin-Rafeeq/AI_Assignments/blob/main/Assignment_Dec_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy and Pandas Practice problems

In [1]:
#1.Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.
import numpy as np
arr = np.arange(1, 21)
matrix = arr.reshape(4, 5)
print(matrix)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [2]:
#2.Create an array of 10 zeros and replace the 5th element with 100.

import numpy as np
arr = np.zeros(10)
arr[4] = 100

print(arr)


[  0.   0.   0.   0. 100.   0.   0.   0.   0.   0.]


In [3]:
#3.Create a NumPy array of even numbers between 2 and 40."

import numpy as np
arr = np.arange(2, 41, 2)

print(arr)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]


In [4]:
#4.Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.

import numpy as np
arr = np.random.randint(1, 101, size=15)

minimum = arr.min()
maximum = arr.max()
mean_val = arr.mean()
std_dev = arr.std()

print("Array:", arr)
print("Min:", minimum)
print("Max:", maximum)
print("Mean:", mean_val)
print("Standard Deviation:", std_dev)


Array: [11 64 17 36 83 91 49 67 50 74 34 23 62 51 52]
Min: 11
Max: 91
Mean: 50.93333333333333
Standard Deviation: 22.74339953090176


In [5]:
#5.Given two arrays of sales and costs, calculate profit and profit percentage arrays.

import numpy as np

sales = np.array([1200, 800, 0, 1500, 950])
costs = np.array([700, 500, 100, 1200, 1000])

profit = sales - costs

with np.errstate(divide='ignore', invalid='ignore'):
    profit_pct = np.where(sales != 0, (profit / sales) * 100, np.nan)

profit_rounded = np.round(profit, 2)
profit_pct_rounded = np.round(profit_pct, 2)

print("Sales:         ", sales)
print("Costs:         ", costs)
print("Profit:        ", profit_rounded)
print("Profit %:      ", profit_pct_rounded)


Sales:          [1200  800    0 1500  950]
Costs:          [ 700  500  100 1200 1000]
Profit:         [ 500  300 -100  300  -50]
Profit %:       [41.67 37.5    nan 20.   -5.26]


In [6]:
#6.Create a 6×6 random matrix and compute row sums, column sums, and total sum.

import numpy as np

matrix = np.random.randint(1, 101, size=(6, 6))

row_sums = matrix.sum(axis=1)
col_sums = matrix.sum(axis=0)
total_sum = matrix.sum()

print("Matrix:\n", matrix)
print("\nRow sums:", row_sums)
print("Column sums:", col_sums)
print("Total sum:", total_sum)


Matrix:
 [[34 29 94 38 24 93]
 [ 7 44 15  1 54 84]
 [94 38 35 45 18 70]
 [62 15 81 83 71 51]
 [36 76 86 45 33 79]
 [14 92 47 10 34 15]]

Row sums: [312 205 300 363 355 212]
Column sums: [247 294 358 222 234 392]
Total sum: 1747


In [7]:
#7.Given stock prices, compute daily returns using vectorized NumPy operations.

import numpy as np

prices = np.array([100, 101.5, 99.0, 100.0, 102.0, 101.0], dtype=float)
simple_returns = prices[1:] / prices[:-1] - 1
log_returns = np.log(prices[1:] / prices[:-1])

print("Prices:         ", prices)
print("Simple returns: ", np.round(simple_returns, 6))
print("Log returns:    ", np.round(log_returns, 6))


Prices:          [100.  101.5  99.  100.  102.  101. ]
Simple returns:  [ 0.015    -0.024631  0.010101  0.02     -0.009804]
Log returns:     [ 0.014889 -0.024939  0.01005   0.019803 -0.009852]


In [8]:
#8.Convert an array of annual interest rates into monthly rates using vectorization.

import numpy as np

annual_rates = np.array([0.03, 0.05, 0.0725, 0.12])
monthly_effective = (1 + annual_rates) ** (1/12) - 1
monthly_nominal = annual_rates / 12

print("Annual rates (%):       ", np.round(annual_rates * 100, 3))
print("Monthly (effective %):  ", np.round(monthly_effective * 100, 4))


Annual rates (%):        [ 3.    5.    7.25 12.  ]
Monthly (effective %):   [0.2466 0.4074 0.585  0.9489]


In [9]:
#9.Normalize a given array of portfolio weights so that the sum becomes 1.

import numpy as np

weights = np.array([0.2, 0.3, 0.15, 0.25, 0.4])

normalized_weights = weights / weights.sum()

print("Original weights:", weights)
print("Normalized weights:", normalized_weights)
print("Sum after normalization:", normalized_weights.sum())


Original weights: [0.2  0.3  0.15 0.25 0.4 ]
Normalized weights: [0.15384615 0.23076923 0.11538462 0.19230769 0.30769231]
Sum after normalization: 1.0


In [10]:
#10.Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]
#a.Find:
#i.mean
#ii.max
#iii.index of the max value

import pandas as pd

data = [1200, 1500, 1800, 2000, 2200]
series = pd.Series(data)

mean_val = series.mean()
max_val = series.max()
max_index = series.idxmax()

print("Series:\n", series)
print("\nMean:", mean_val)
print("Max:", max_val)
print("Index of max value:", max_index)


Series:
 0    1200
1    1500
2    1800
3    2000
4    2200
dtype: int64

Mean: 1740.0
Max: 2200
Index of max value: 4


In [14]:
#11.Create a DataFrame with Student Name + 3 subject marks:
#Name | Math | Science | English
#Then:
#Print only the Math column
#Print first 2 rows
#Print the shape

import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 90, 78],
    "Science": [88, 76, 92],
    "English": [80, 85, 89]
}

df = pd.DataFrame(data)

print("Math column:\n", df["Math"])
print("\nFirst 2 rows:\n", df.head(2))
print("\nShape of DataFrame:", df.shape)


Math column:
 0    85
1    90
2    78
Name: Math, dtype: int64

First 2 rows:
     Name  Math  Science  English
0  Alice    85       88       80
1    Bob    90       76       85

Shape of DataFrame: (3, 4)


In [15]:
#12.Using this DataFrame:
#df = pd.DataFrame({
 #   "Account": [101,102,103,104],
  #  "Balance": [5000, 15000, 7000, 12000]
#})
#Filter rows where:
#Balance > 8000
#Balance between 6000 and 13000

import pandas as pd

df = pd.DataFrame({
    "Account": [101, 102, 103, 104],
    "Balance": [5000, 15000, 7000, 12000]
})

filter_gt_8000 = df[df["Balance"] > 8000]

filter_between = df[(df["Balance"] >= 6000) & (df["Balance"] <= 13000)]

print("Original DataFrame:\n", df)
print("\nBalance > 8000:\n", filter_gt_8000)
print("\nBalance between 6000 and 13000:\n", filter_between)


Original DataFrame:
    Account  Balance
0      101     5000
1      102    15000
2      103     7000
3      104    12000

Balance > 8000:
    Account  Balance
1      102    15000
3      104    12000

Balance between 6000 and 13000:
    Account  Balance
2      103     7000
3      104    12000
